version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "/"
      - "/examples/*"
      - "/examples/*/*"
      - "/examples/*/*/*"
    schedule:
      interval: weekly
    groups:
      rust:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
