version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "/"
      - "/examples/*"
      - "/examples/*/*"
      - "/examples/*/*/*"
    schedule:
      interval: monthly
    groups:
      rust:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directories:
      - "/books/*/src/examples/**/*"
    schedule:
      interval: monthly
    groups:
      books:
        patterns:
          - "*"


  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
