[package]
name = "create-select"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = "2.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }
