[package]
name = "remove-namespace"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = { version = "1.4.0", features = ["sql2"] }
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }
