[book]
authors = ["Gabor Szabo"]
language = "en"
multilingual = false
src = "src"
title = "Error handling in Rust"

# Handle Youtube video embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by [Gábor Szabó](https://szabgab.com/)"

