[book]
authors = ["Gabor Szabo"]
language = "en"
src = "src"
title = "The Clap book"

# Add github icon to the menu
[output.html]
git-repository-url = "https://github.com/szabgab/rust.code-maven.com"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/szabgab/rust.code-maven.com/edit/main/books/clap/{path}"

# Handle Youtube video embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by [Gábor Szabó](https://szabgab.com/)"




