[package]
name = "connect-to-server"
version = "0.1.0"
edition = "2024"

[dependencies]
surrealdb = "2.0"
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
