[package]
name = "tera-filter"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5"
rocket_dyn_templates = { version = "0.2.0", features = ["tera"] }
serde_json = "1.0.128"
tera = "1.20.0"

