name: Check Rust slides
on:
  push:
    paths:
      - slides/**
  workflow_dispatch:

# Running these checks on GitHub Actions takes 10 minutes. It is a waste of time if the files have not changed.

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site source
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "$ALL_CHANGED_FILES"
          echo "------"
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
          CHHANGED_FOLDERS=$(perl -E'say join " ", grep { $_ ne "" and not $uniq{$_}++ } map {m{(/examples/[^/]+/[^/]+)}; $1}  @ARGV' $ALL_CHANGED_FILES)
          echo "$CHANGED_FOLDERS"
      - name: Check the slides
        run: |
          echo "$CHANGED_FOLDERS"
          cd slides/rust
          # comment out as it takes 10 minutes to run
          # maybe we could improve it by sharing some of the binaries and/or caching
          ./check.sh --verbose --fmt $CHANGED_FOLDERS
