name: Check Rust slides
on:
  push:
    paths:
      - slides/**
  workflow_dispatch:

# Running these checks on GitHub Actions takes 10 minutes. It is a waste of time if the files have not changed.

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site source
        uses: actions/checkout@v5

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "$ALL_CHANGED_FILES"
          echo "------"
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
          CHANGED_FOLDERS=$(perl -E'say join " ", grep { $_ ne "" and not $uniq{$_}++ } map {m{/(examples/[^/]+/[^/]+)}; $1}  @ARGV' $ALL_CHANGED_FILES)
          echo "CHANGED_FOLDERS: $CHANGED_FOLDERS"
          echo $CHANGED_FOLDERS > folders.txt
      - name: Check the slides
        run: |
          CHANGED_FOLDERS=$(cat folders.txt)
          echo "CHANGED_FOLDERS: $CHANGED_FOLDERS"
          # cd slides/rust
          # # comment out as it takes 10 minutes to run
          # # maybe we could improve it by sharing some of the binaries and/or caching
          # if [ "$CHANGED_FOLDERS" != "" ]; then
          #   ./check.sh --verbose --cleanup --use-examples --check $CHANGED_FOLDERS
          # fi
