name: Check Rust slides
on:
  push:
    paths:
      - slides/**
  workflow_dispatch:

# Running these checks on GitHub Actions takes 10 minutes. It is a waste of time if the files have not changed.

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site source
        uses: actions/checkout@v4

      - name: Check the slides
        run: |
          cd slides/rust
          # comment out as it takes 10 minutes to run
          # maybe we could improve it by sharing some of the binaries and/or caching
          #./check.sh
